export const dsKhoa = [
  "Nội tổng quát",
  "Ngoại tổng quát",
  "Sản",
  "Nhi",
  "Cấp cứu",
  "Hồi sức cấp cứu",
  "Xét nghiệm",
  "Chẩn đoán hình ảnh",
  "Gây mê hồi sức",
  "Da liễu",
  "Răng hàm mặt",
  "Mắt",
  "Tai mũi họng",
  "Nội tiết",
  "Tim mạch",
  "Thận - tiết niệu",
  "Hô hấp",
  "Tâm lý",
  "Vật lý trị liệu",
  "Phục hồi chức năng",
  "Dinh dưỡng",
  "Y học cổ truyền",
  "Ung bướu",
  "Huyết học - truyền máu",
  "Sinh lý bệnh",
  "Y học thể thao",
  "Y học gia đình",
  "Sức khỏe cộng đồng",
  "Y học dự phòng",
  "Y học lao động",
  "Di truyền",
  "Dị ứng - miễn dịch lâm sàng",
];
